[] execVM "video\film.sqf";
leaFunction =  compile preprocessFileLineNumbers "lea\loadout-init.sqf"; call leaFunction;//line generated by LEA.

//revive
call compileFinal preprocessFileLineNumbers "FAR_revive\FAR_revive_init.sqf";
waitUntil{!(isNil "BIS_fnc_init")};

//Ingame-Tags
[] execVM "tags.sqf";

//Unterdrückungsskript
null = [3] execvm "tpwcas\tpwcas_script_init.sqf";

//Gruppenmarker
[] execVM "Scripts\markers.sqf";


//////////////////////////////////////
////// Headless Client statisch //////
//////////////////////////////////////

if not (isDedicated) then {
        if (isNull player) then {
    	waitUntil {!isNull player};
    };

if (str player == "HeadlessClient") then {
        execVM "HcCore\HCInit.sqf";
    } else {
        hideObject HeadlessClient;
        headlessClient enableSimulation false;
        
       };
};

HCName = "HClient";

if (isserver) then {execVM "basis.sqf";};
if (isserver) then {execVM "Zaros.sqf";};

//////////////////////////////////////
////////   Syncronisierung   /////////
//////////////////////////////////////

waituntil {!isnil "bis_fnc_init"};
finishMissionInit;
enableRadio false;
_camera = "camera" camCreate [(getPos player select 0),(getPos player select 1),200];
_camera cameraEffect ["internal","back"];
_camera camSetFOV 0.700;
_camera camCommit 0;
waitUntil {camCommitted _camera};
cutText["Synchronisiere, bitte warten . . .", "BLACK FADED", 10];
waitUntil {time > 12};
cutText["Headless Client initialisieren . . .", "BLACK FADED", 10];
waitUntil {time > 20};
cutText["Ambient Combat Script aktivieren . . .", "BLACK FADED", 10];
waitUntil {time > 28};
player cameraEffect ["terminate","back"];
camDestroy _camera;
waitUntil {time > 30};
cutText["", "BLACK IN", 0];
enableRadio true;